---
# tasks file for metal-setup

- name: Log into DockerHub
  community.docker.docker_login:
    username: "{{ metal_docker_username }}"
    password: "{{ metal_docker_access_token }}"

- name: Register METAL GCP Application Service
  ansible.builtin.template:
    src: "{{ role_path }}/templates/metal-men-gcp.yaml.j2"
    dest: "{{ matrix_synapse_config_dir_path }}/metal-men-gcp.yaml"
    mode: 0644